#!/usr/bin/env python3
"""class-ticket-builder.py — class-level queue source (phase.rs adoption).

Turns the ranked coverage plan (corpus/build-plan.jsonl) into [VOCAB] round
tickets on Kanboard — one ticket per missing-primitive CLASS with unlock
count, examples and the quality-gate DoD — instead of per-card bug tickets.
The dispatcher already routes [VOCAB] tickets; no new routing needed.

  class-ticket-builder.py            # dry-run
  class-ticket-builder.py --commit   # create up to MAX_NEW tickets
  class-ticket-builder.py --refresh  # re-run coverage_planner first
"""
import json, os, subprocess, sys

REPO = os.environ.get("REPO_DIR", "/opt/development/magic-new")
KB_URL = os.environ.get("KB_URL", "https://kanboard.k.ezq.ch/jsonrpc.php")
KB_USER = os.environ.get("KB_USER", "admin")
KB_TOKEN = os.environ.get("KB_TOKEN", "fda650985874506da62a737b9a7befc39a5873735a253de80fa2d5ee5c20")
PROJECT = int(os.environ.get("PROJECT_ID", "2"))
COL_PRIO = int(os.environ.get("COL_PRIORITY", "19"))
MAX_NEW = int(os.environ.get("MAX_NEW", "3"))
MIN_UNLOCK = int(os.environ.get("MIN_UNLOCK", "30"))
COMMIT = "--commit" in sys.argv

def kb(method, params):
    body = json.dumps({"jsonrpc": "2.0", "id": 1, "method": method, "params": params})
    out = subprocess.run(["curl", "-fsS", "-u", f"{KB_USER}:{KB_TOKEN}",
                          "-H", "Content-Type: application/json",
                          "-d", body, KB_URL], capture_output=True, text=True)
    if out.returncode != 0:
        sys.exit(f"kanboard API failed: {out.stderr[:200]}")
    return json.loads(out.stdout).get("result")

if "--refresh" in sys.argv:
    subprocess.run(["python3", "scripts/paragraph/coverage_planner.py", "-n", "80"],
                   cwd=REPO, check=False, capture_output=True)

plan = [json.loads(l) for l in open(f"{REPO}/corpus/build-plan.jsonl")]
open_titles = " | ".join(t.get("title", "") for t in
                         (kb("getAllTasks", {"project_id": PROJECT, "status_id": 1}) or []))

made = 0
for row in plan:
    if made >= MAX_NEW:
        break
    item, unlock = row.get("item", ""), row.get("marginal_unlock", 0)
    if not item or unlock < MIN_UNLOCK:
        continue
    if item in open_titles:
        continue  # dedup: an open ticket already names this class
    title = f"[VOCAB] {item} — class round (unlock {unlock})"
    desc = f"""CLASS ROUND (auto-generated by class-ticket-builder.py, phase.rs regime).

Item: {item}
Marginal unlock: {unlock} review cards
Examples: {', '.join(row.get('examples', [])[:5])}

Build the CLASS, not a card: one primitive/emitter/executor covering this
whole item. Follow the QUALITY GATES in your system prompt (premise from the
carddb record text; EXISTENCE_CHECK 5-grep line BEFORE any new primitive;
honest miss over silently wrong; discriminating test through the real
pipeline). Evidence: corpus/build-plan.jsonl, corpus/primitive-inventory.json,
docs/phase-rs-factory-analysis.md.

DoD: executor+registry+shape test green (go test ./cards/... ./game/...),
reparse.py emitter wired, eligible review cards flipped via the standard
flip protocol with a round tag, honest misses reported with named reasons.
"""
    if COMMIT:
        tid = kb("createTask", {"project_id": PROJECT, "title": title,
                                "description": desc, "column_id": COL_PRIO,
                                "priority": 3})
        print(f"CREATED #{tid}: {title}")
    else:
        print(f"WOULD CREATE: {title}")
    made += 1

print(f"{'created' if COMMIT else 'candidates'}={made}")
